#include <stdio.h>
#include <stdlib.h>

/**
 * main - fibonacci sequence is generated by adding
 * the previous two terms
 *
 * Return: 0
 */
int main(void)
{
	int count, i, j, m;

	i = 1;
	j = 2;
	for (count = 1; count <= 50; count++)
	{
		if (count == 1)
			_putchar (i);
		if (count == 2)
			_putchar (j);
		if (count != 1 && count != 2)
		{
			m = i + j;
			printf("%d", m);
			i = j;
			j = m;
		}
	}
	printf("\n");
	return (0);
}
