#include <stdio.h>

/**
 * main - finds and prints the sum of the even-valued terms,
 * followed by a new line.
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms.
 * By considering the terms in the Fibonacci
 * sequence whose values do not exced 4,000,000.
 *
 * Return: 0
 */
int main(void)
{
	unsigned int value1 = 0, value2 = 1, valuesum;
	float sum;

	while (1)
	{
		valuesum = value1 + value2;
		if (valuesum  > 4000000)
			break;
		if ((valuesum % 2) == 0)
			sum += valuesum;
		value1 = value2;
		value2 = valuesum;
	}
	printf("%.0f\n", sum);
	return (0);
}
